name: Onionz
version: 1.0
author: Unionjackjz1
main: me.Unionjackjz1.Framework.Main
commands:
  framework:
    usage: /<command>
    description: Main framework command
permissions:
  onion.commands:
    default: op